#!/bin/sh
# May at somepoint want to do this `date +%Y%m%d%H%M%S` for a version
usage() {
	echo "usage: bump-version <version-id>"
}

if [ $# -ne 1 ]; then
	usage
	exit 1
fi

echo flex-slurm-$1 > VERSION

git add VERSION
git commit -m "Bumped version number to $1"
